// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 8c83a684a486c897defe2860b759281c7247cac4a1eabc2cb8793d2376306504
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *BuilderPreferences to SSZ-encoded bytes.
func (t *BuilderPreferences) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *BuilderPreferences to SSZ-encoded bytes, appending to the provided buffer.
func (t *BuilderPreferences) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BuilderPreferences)
	}
	{ // Static Field #0 'MaxTrustedBid'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.MaxTrustedBid))
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *BuilderPreferences from SSZ-encoded bytes.
func (t *BuilderPreferences) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 8 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 8)
	}
	{ // Field #0 'MaxTrustedBid' (static)
		buf := buf[0:8]
		t.MaxTrustedBid = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *BuilderPreferences.
func (t *BuilderPreferences) SizeSSZ() (size int) {
	return 8
}

// HashTreeRoot computes the SSZ hash tree root of the *BuilderPreferences.
func (t *BuilderPreferences) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *BuilderPreferences using the given hash walker.
func (t *BuilderPreferences) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BuilderPreferences)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'MaxTrustedBid'
		hh.PutUint64(uint64(t.MaxTrustedBid))
	}
	hh.Merkleize(idx)
	return nil
}
