// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: e128b147f7601066c179c0b88cf4afd22079ea6f57687ed90d2ce3cd08ef0feb
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *BuilderPreferencesRequest to SSZ-encoded bytes.
func (t *BuilderPreferencesRequest) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *BuilderPreferencesRequest to SSZ-encoded bytes, appending to the provided buffer.
func (t *BuilderPreferencesRequest) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BuilderPreferencesRequest)
	}
	{ // Static Field #0 'Preferences'
		t := t.Preferences
		if t == nil {
			t = new(BuilderPreferences)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Preferences")
		}
	}
	{ // Static Field #1 'Auth'
		t := t.Auth
		if t == nil {
			t = new(SignedRequestAuth)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Auth")
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *BuilderPreferencesRequest from SSZ-encoded bytes.
func (t *BuilderPreferencesRequest) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 160 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 160)
	}
	{ // Field #0 'Preferences' (static)
		buf := buf[0:8]
		if t.Preferences == nil {
			t.Preferences = new(BuilderPreferences)
		}
		if err = t.Preferences.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Preferences")
		}
	}
	{ // Field #1 'Auth' (static)
		buf := buf[8:160]
		if t.Auth == nil {
			t.Auth = new(SignedRequestAuth)
		}
		if err = t.Auth.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Auth")
		}
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *BuilderPreferencesRequest.
func (t *BuilderPreferencesRequest) SizeSSZ() (size int) {
	return 160
}

// HashTreeRoot computes the SSZ hash tree root of the *BuilderPreferencesRequest.
func (t *BuilderPreferencesRequest) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *BuilderPreferencesRequest using the given hash walker.
func (t *BuilderPreferencesRequest) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BuilderPreferencesRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Preferences'
		t := t.Preferences
		if t == nil {
			t = new(BuilderPreferences)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Preferences")
		}
	}
	{ // Field #1 'Auth'
		t := t.Auth
		if t == nil {
			t = new(SignedRequestAuth)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Auth")
		}
	}
	hh.Merkleize(idx)
	return nil
}
