// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 6fa8a329ecf5abb65bb6c9572e191b5b4a0d47f2b9e514723ad9c793a8e11ef6
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *RequestAuth to SSZ-encoded bytes.
func (t *RequestAuth) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *RequestAuth to SSZ-encoded bytes, appending to the provided buffer.
func (t *RequestAuth) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(RequestAuth)
	}
	dstlen := len(dst)
	// Offset Field #0 'BuilderURL'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	{ // Dynamic Field #0 'BuilderURL'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		vlen := len(t.BuilderURL)
		if vlen > 2048 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 2048), "BuilderURL")
		}
		dst = append(dst, t.BuilderURL[:]...)
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *RequestAuth from SSZ-encoded bytes.
func (t *RequestAuth) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 12 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 12)
	}
	// Field #0 'BuilderURL' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 12 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 12), "BuilderURL:o")
	}
	{ // Field #1 'Slot' (static)
		buf := buf[4:12]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #0 'BuilderURL' (dynamic)
		buf := buf[offset0:]
		if len(buf) > 2048 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(len(buf), 2048), "BuilderURL")
		}
		t.BuilderURL = sszutils.ExpandSlice(t.BuilderURL, len(buf))
		copy(t.BuilderURL[:], buf)
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *RequestAuth.
func (t *RequestAuth) SizeSSZ() (size int) {
	if t == nil {
		t = new(RequestAuth)
	}
	// Field #0 'BuilderURL' offset (4 bytes)
	// Field #1 'Slot' static (8 bytes)
	size += 12
	{ // Dynamic field #0 'BuilderURL'
		size += len(t.BuilderURL)
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *RequestAuth.
func (t *RequestAuth) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *RequestAuth using the given hash walker.
func (t *RequestAuth) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(RequestAuth)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'BuilderURL'
		vlen := uint64(len(t.BuilderURL))
		if vlen > 2048 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 2048), "BuilderURL")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		hh.AppendBytes32(t.BuilderURL[:])
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(2048, vlen, 1))
	}
	{ // Field #1 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	hh.Merkleize(idx)
	return nil
}
