// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: dee1013b9a1f5a2dbbc1a99cf09309663545ed8b982cd736d3e3126dd7197b9e
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *RequestAuth to SSZ-encoded bytes.
func (t *RequestAuth) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *RequestAuth to SSZ-encoded bytes, appending to the provided buffer.
func (t *RequestAuth) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(RequestAuth)
	}
	{ // Static Field #0 'BuilderPubkey'
		dst = append(dst, t.BuilderPubkey[:48]...)
	}
	{ // Static Field #1 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *RequestAuth from SSZ-encoded bytes.
func (t *RequestAuth) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 56 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 56)
	}
	{ // Field #0 'BuilderPubkey' (static)
		buf := buf[0:48]
		copy(t.BuilderPubkey[:], buf)
	}
	{ // Field #1 'Slot' (static)
		buf := buf[48:56]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *RequestAuth.
func (t *RequestAuth) SizeSSZ() (size int) {
	return 56
}

// HashTreeRoot computes the SSZ hash tree root of the *RequestAuth.
func (t *RequestAuth) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *RequestAuth using the given hash walker.
func (t *RequestAuth) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(RequestAuth)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'BuilderPubkey'
		hh.PutBytes(t.BuilderPubkey[:48])
	}
	{ // Field #1 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	hh.Merkleize(idx)
	return nil
}
