// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: fbe1741a8b3f05320b16680642ce271250442ea6f1c24fed1294b0215030b090
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *SignedRequestAuth to SSZ-encoded bytes.
func (t *SignedRequestAuth) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *SignedRequestAuth to SSZ-encoded bytes, appending to the provided buffer.
func (t *SignedRequestAuth) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedRequestAuth)
	}
	{ // Static Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(RequestAuth)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Message")
		}
	}
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *SignedRequestAuth from SSZ-encoded bytes.
func (t *SignedRequestAuth) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 152 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 152)
	}
	{ // Field #0 'Message' (static)
		buf := buf[0:56]
		if t.Message == nil {
			t.Message = new(RequestAuth)
		}
		if err = t.Message.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Message")
		}
	}
	{ // Field #1 'Signature' (static)
		buf := buf[56:152]
		copy(t.Signature[:], buf)
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *SignedRequestAuth.
func (t *SignedRequestAuth) SizeSSZ() (size int) {
	return 152
}

// HashTreeRoot computes the SSZ hash tree root of the *SignedRequestAuth.
func (t *SignedRequestAuth) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *SignedRequestAuth using the given hash walker.
func (t *SignedRequestAuth) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedRequestAuth)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(RequestAuth)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Message")
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}
